apiVersion: v1
kind: Service
metadata:
  name: polybot-service
  namespace: prod
spec:
  selector:
    app: polybot
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8443
  type: ClusterIP