apiVersion: apps/v1
kind: Deployment
metadata:
  name: yolo
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yolo
  template:
    metadata:
      labels:
        app: yolo
    spec:
      containers:
      - name: yolo
        image: ameerarayan/yoloservice-dev:42
        ports:
        - containerPort: 8000