name: Deploy Nginx Prod Config

on:
  push:
    branches:
      - main
    paths:
      - 'nginx-config/prod.conf'

jobs:
  deploy-nginx-prod:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Copy prod.conf to Nginx EC2 (Prod)
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.NGINX_PROD_HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "nginx-config/prod.conf"
          target: "/etc/nginx/conf.d/"
          overwrite: true

      - name: Reload Nginx on Prod EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.NGINX_PROD_HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo nginx -t
            sudo systemctl reload nginx