name: Deploy Nginx Dev config

on:
  push:
    branches:
      - dev

jobs:
  deploy-nginx-dev:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Copy config to home folder on EC2
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.NGINX_DEV_HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "nginx-config/default.conf"
          target: "~/default.conf"
          overwrite: true

      - name: Move config to nginx and reload
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.NGINX_DEV_HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo mv ~/default.conf /etc/nginx/conf.d/default.conf
            sudo nginx -t
            sudo systemctl reload nginx