name: Deploy Nginx Prod Config

on:
  push:
    branches:
      - main

jobs:
  deploy-nginx-prod:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Copy config to home folder on EC2
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.NGINX_PROD_HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "nginx-config/prod.conf"
          target: "~/prod.conf"
          overwrite: true

      - name: Move config to nginx and reload
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.NGINX_PROD_HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo mv ~/prod.conf /etc/nginx/conf.d/prod.conf
            sudo nginx -t
            sudo systemctl reload nginx