name: Initialize Kubernetes Cluster

on:
  workflow_dispatch:

  workflow_run:
    workflows: ["Provision K8s Infrastructure"]
    types:
      - completed

jobs:
  init-k8s:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
    - name: Connect via SSH and run kubeadm init, then save join command
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.CONTROL_PLANE_IP }}
        username: ubuntu
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          # Step 1: Init Kubernetes Cluster
          curl -O https://raw.githubusercontent.com/AmeeraRayan/PolybotInfra/main/scripts/kubeadm-init.sh
          chmod +x kubeadm-init.sh
          ./kubeadm-init.sh

          # Step 2: Get the kubeadm join command
          kubeadm token create --print-join-command > /tmp/k8s_join.sh

          # Step 3: Install AWS CLI (if not already)
          if ! command -v aws &> /dev/null; then
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install
          fi

          # Step 4: Save the command to Secrets Manager (create or update)
          aws secretsmanager create-secret \
            --name K8S_JOIN_COMMAND \
            --secret-string file:///tmp/k8s_join.sh \
            --region eu-north-1 || \
          aws secretsmanager put-secret-value \
            --secret-id K8S_JOIN_COMMAND \
            --secret-string file:///tmp/k8s_join.sh \
            --region eu-north-1