name: Provision Control Plane Infrastructure

on:
  push:
    branches:
      - main

jobs:
  provision:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.6.6

    - name: Terraform Init
      run: terraform -chdir=tf init

    - name: Terraform Apply
      run: terraform -chdir=tf apply -var-file=tf/region.eu-north-1.tfvars -auto-approve