name: Provision K8s Infrastructure

on:
  push:
    branches:
      - main

jobs:
  provision:
    name: Terraform Apply Infra
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: cd tf && terraform plan -var-file="region.eu-north-1.tfvars"

      - name: Terraform Apply
        run: cd tf && terraform apply -auto-approve -var-file="region.eu-north-1.tfvars"